services:
  - type: web
    name: globeconnect-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://globeconnect-client.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true

  - type: static
    name: globeconnect-client
    buildCommand: cd client && npm install && npm run build
    publishDir: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://globeconnect-api.onrender.com
      - key: REACT_APP_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
