services:
  - type: web
    name: globeconnect-api
    env: node
    plan: free
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
      mkdir -p ../server/public
      cp -r build/* ../server/public/
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://globeconnect-client.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    staticPublishPath: ./server/public
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /public/index.html
